import {
  Banknote,
  BookOpen,
  Briefcase,
  Bus,
  Car,
  CircleEllipsis,
  CirclePlus,
  Clapperboard,
  Coffee,
  CreditCard,
  Dumbbell,
  Fuel,
  Gift,
  GraduationCap,
  HeartPulse,
  House,
  Landmark,
  Laptop,
  PawPrint,
  Percent,
  PiggyBank,
  Plane,
  Repeat,
  Shirt,
  ShoppingBag,
  ShoppingBasket,
  Smartphone,
  Sparkles,
  Tag,
  TrendingUp,
  Undo2,
  Utensils,
  Wallet,
  Wifi,
  Zap,
} from 'lucide-react';

// Icons are stored by name (e.g. "shopping-basket"). Only these are bundled — importing
// every lucide icon would add hundreds of KB. Unknown names fall back to a tag.
export const ICONS = {
  banknote: Banknote,
  'book-open': BookOpen,
  briefcase: Briefcase,
  bus: Bus,
  car: Car,
  'circle-ellipsis': CircleEllipsis,
  'circle-plus': CirclePlus,
  clapperboard: Clapperboard,
  coffee: Coffee,
  'credit-card': CreditCard,
  dumbbell: Dumbbell,
  fuel: Fuel,
  gift: Gift,
  'graduation-cap': GraduationCap,
  'heart-pulse': HeartPulse,
  house: House,
  landmark: Landmark,
  laptop: Laptop,
  'paw-print': PawPrint,
  percent: Percent,
  'piggy-bank': PiggyBank,
  plane: Plane,
  repeat: Repeat,
  shirt: Shirt,
  'shopping-bag': ShoppingBag,
  'shopping-basket': ShoppingBasket,
  smartphone: Smartphone,
  sparkles: Sparkles,
  tag: Tag,
  'trending-up': TrendingUp,
  'undo-2': Undo2,
  utensils: Utensils,
  wallet: Wallet,
  wifi: Wifi,
  zap: Zap,
};

export function iconFor(name) {
  return ICONS[name] ?? Tag;
}
